# Generated by Django 4.2a1 on 2023-02-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='color',
            new_name='prodtype',
        ),
    ]
